name: build
on: [push, pull_request, workflow_dispatch]

jobs:
  pylance:
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: python -m pip install -Ur requirements.txt
      - name: Install Pyright
        run: python -m pip install -U pyright
      - name: Test with Pyright
        run: pyright --lib my_evil_twin
